version: "3.8"
services:
  database:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "${HOME}/Documents/dev/golang/src/flavioltonon/testgrounds/.data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      # If authentication fails, try running mysql directly and executing the following commands:
      # ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourRootPassword';
      # -- or
      # CREATE USER 'foo'@'%' IDENTIFIED WITH mysql_native_password BY 'bar';
      # -- then
      # FLUSH PRIVILEGES;